---
# can be left alone for aws `c5ad.4xlarge` instance type
# If the machine is different or not AWS, then get the unmounted disks using `fdisk -l` and modify the list
raw_disk_list: ["/dev/nvme1n1", "/dev/nvme2n1"]
# Set to false if you want to manually setup the disks before running the playbook
setup_disks: true
# Default 32 GB
swap_mb: 32000
# AWS managed prometheus url for local agent to write data to
aws_prometheus_remote_write_url: "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-112093cd-2aee-4617-ab97-10e00698e139/api/v1/remote_write"
# Region for AWS managed prometheus
aws_region: "us-east-1"
# Label for filtering data in grafana
aws_prometheus_monitoring_label: "sov-nikolai01"
