name: E2E
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  e2e:
    timeout-minutes: 15
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3.5.1
        with:
          node-version: "18.16"
      - run: yarn install --frozen-lockfile
      - name: Download Polkadot and parachain binaries
        run: |
          wget --no-verbose https://github.com/paritytech/cumulus/releases/download/v0.9.420/polkadot-parachain
          wget --no-verbose https://github.com/paritytech/polkadot/releases/download/v0.9.42/polkadot
          chmod +x ./polkadot*
        working-directory: e2e
      - name: Run a local relaychain with a parachain using zombienet
        run: |
          export PATH=$(pwd):$PATH
          npx --yes @zombienet/cli@1.3.43 \
            --provider native spawn zombienet.native.toml \
            > polkadot.txt 2>&1 &
          source wait_until.sh 'curl -s "127.0.0.1:9933"'
          source wait_until.sh 'curl -s "127.0.0.1:9934"'
        working-directory: e2e
      - name: Build faucet
        run: yarn build:docker
      - name: Run the E2E tests
        run: yarn test:e2e
      - name: Debug Polkadot logs
        if: failure()
        run: cat e2e/polkadot.txt
      - name: Debug Matrix logs
        if: failure()
        run: cat e2e/containter_logs/faucet-test-matrix.log
      - name: Debug faucet logs
        if: failure()
        run: cat e2e/containter_logs/faucet-test-app.log
