/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutQueriesImport } from './routes/_layout/queries'
import { Route as LayoutExtrinsicsImport } from './routes/_layout/extrinsics'
import { Route as LayoutExplorerImport } from './routes/_layout/explorer'
import { Route as LayoutAccountsImport } from './routes/_layout/accounts'
import { Route as LayoutUtilitiesIndexImport } from './routes/_layout/utilities/index'
import { Route as LayoutUtilitiesLayoutImport } from './routes/_layout/utilities/_layout'
import { Route as LayoutUtilitiesLayoutPlanckConvertorImport } from './routes/_layout/utilities/_layout/planck-convertor'

// Create Virtual Routes

const LayoutUtilitiesImport = createFileRoute('/_layout/utilities')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutUtilitiesRoute = LayoutUtilitiesImport.update({
  path: '/utilities',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutQueriesRoute = LayoutQueriesImport.update({
  path: '/queries',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExtrinsicsRoute = LayoutExtrinsicsImport.update({
  path: '/extrinsics',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutExplorerRoute = LayoutExplorerImport.update({
  path: '/explorer',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAccountsRoute = LayoutAccountsImport.update({
  path: '/accounts',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutUtilitiesIndexRoute = LayoutUtilitiesIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutUtilitiesRoute,
} as any)

const LayoutUtilitiesLayoutRoute = LayoutUtilitiesLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutUtilitiesRoute,
} as any)

const LayoutUtilitiesLayoutPlanckConvertorRoute =
  LayoutUtilitiesLayoutPlanckConvertorImport.update({
    path: '/planck-convertor',
    getParentRoute: () => LayoutUtilitiesLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/accounts': {
      id: '/_layout/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof LayoutAccountsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/explorer': {
      id: '/_layout/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof LayoutExplorerImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/extrinsics': {
      id: '/_layout/extrinsics'
      path: '/extrinsics'
      fullPath: '/extrinsics'
      preLoaderRoute: typeof LayoutExtrinsicsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/queries': {
      id: '/_layout/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof LayoutQueriesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/utilities': {
      id: '/_layout/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof LayoutUtilitiesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/utilities/_layout': {
      id: '/_layout/utilities/_layout'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof LayoutUtilitiesLayoutImport
      parentRoute: typeof LayoutUtilitiesRoute
    }
    '/_layout/utilities/': {
      id: '/_layout/utilities/'
      path: '/'
      fullPath: '/utilities/'
      preLoaderRoute: typeof LayoutUtilitiesIndexImport
      parentRoute: typeof LayoutUtilitiesImport
    }
    '/_layout/utilities/_layout/planck-convertor': {
      id: '/_layout/utilities/_layout/planck-convertor'
      path: '/planck-convertor'
      fullPath: '/utilities/planck-convertor'
      preLoaderRoute: typeof LayoutUtilitiesLayoutPlanckConvertorImport
      parentRoute: typeof LayoutUtilitiesLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutUtilitiesLayoutRouteChildren {
  LayoutUtilitiesLayoutPlanckConvertorRoute: typeof LayoutUtilitiesLayoutPlanckConvertorRoute
}

const LayoutUtilitiesLayoutRouteChildren: LayoutUtilitiesLayoutRouteChildren = {
  LayoutUtilitiesLayoutPlanckConvertorRoute:
    LayoutUtilitiesLayoutPlanckConvertorRoute,
}

const LayoutUtilitiesLayoutRouteWithChildren =
  LayoutUtilitiesLayoutRoute._addFileChildren(
    LayoutUtilitiesLayoutRouteChildren,
  )

interface LayoutUtilitiesRouteChildren {
  LayoutUtilitiesLayoutRoute: typeof LayoutUtilitiesLayoutRouteWithChildren
  LayoutUtilitiesIndexRoute: typeof LayoutUtilitiesIndexRoute
}

const LayoutUtilitiesRouteChildren: LayoutUtilitiesRouteChildren = {
  LayoutUtilitiesLayoutRoute: LayoutUtilitiesLayoutRouteWithChildren,
  LayoutUtilitiesIndexRoute: LayoutUtilitiesIndexRoute,
}

const LayoutUtilitiesRouteWithChildren = LayoutUtilitiesRoute._addFileChildren(
  LayoutUtilitiesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAccountsRoute: typeof LayoutAccountsRoute
  LayoutExplorerRoute: typeof LayoutExplorerRoute
  LayoutExtrinsicsRoute: typeof LayoutExtrinsicsRoute
  LayoutQueriesRoute: typeof LayoutQueriesRoute
  LayoutUtilitiesRoute: typeof LayoutUtilitiesRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAccountsRoute: LayoutAccountsRoute,
  LayoutExplorerRoute: LayoutExplorerRoute,
  LayoutExtrinsicsRoute: LayoutExtrinsicsRoute,
  LayoutQueriesRoute: LayoutQueriesRoute,
  LayoutUtilitiesRoute: LayoutUtilitiesRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/accounts': typeof LayoutAccountsRoute
  '/explorer': typeof LayoutExplorerRoute
  '/extrinsics': typeof LayoutExtrinsicsRoute
  '/queries': typeof LayoutQueriesRoute
  '/utilities': typeof LayoutUtilitiesLayoutRouteWithChildren
  '/utilities/': typeof LayoutUtilitiesIndexRoute
  '/utilities/planck-convertor': typeof LayoutUtilitiesLayoutPlanckConvertorRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/accounts': typeof LayoutAccountsRoute
  '/explorer': typeof LayoutExplorerRoute
  '/extrinsics': typeof LayoutExtrinsicsRoute
  '/queries': typeof LayoutQueriesRoute
  '/utilities': typeof LayoutUtilitiesIndexRoute
  '/utilities/planck-convertor': typeof LayoutUtilitiesLayoutPlanckConvertorRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/accounts': typeof LayoutAccountsRoute
  '/_layout/explorer': typeof LayoutExplorerRoute
  '/_layout/extrinsics': typeof LayoutExtrinsicsRoute
  '/_layout/queries': typeof LayoutQueriesRoute
  '/_layout/utilities': typeof LayoutUtilitiesRouteWithChildren
  '/_layout/utilities/_layout': typeof LayoutUtilitiesLayoutRouteWithChildren
  '/_layout/utilities/': typeof LayoutUtilitiesIndexRoute
  '/_layout/utilities/_layout/planck-convertor': typeof LayoutUtilitiesLayoutPlanckConvertorRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/accounts'
    | '/explorer'
    | '/extrinsics'
    | '/queries'
    | '/utilities'
    | '/utilities/'
    | '/utilities/planck-convertor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/accounts'
    | '/explorer'
    | '/extrinsics'
    | '/queries'
    | '/utilities'
    | '/utilities/planck-convertor'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/accounts'
    | '/_layout/explorer'
    | '/_layout/extrinsics'
    | '/_layout/queries'
    | '/_layout/utilities'
    | '/_layout/utilities/_layout'
    | '/_layout/utilities/'
    | '/_layout/utilities/_layout/planck-convertor'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/accounts",
        "/_layout/explorer",
        "/_layout/extrinsics",
        "/_layout/queries",
        "/_layout/utilities"
      ]
    },
    "/_layout/accounts": {
      "filePath": "_layout/accounts.tsx",
      "parent": "/_layout"
    },
    "/_layout/explorer": {
      "filePath": "_layout/explorer.tsx",
      "parent": "/_layout"
    },
    "/_layout/extrinsics": {
      "filePath": "_layout/extrinsics.tsx",
      "parent": "/_layout"
    },
    "/_layout/queries": {
      "filePath": "_layout/queries.tsx",
      "parent": "/_layout"
    },
    "/_layout/utilities": {
      "filePath": "_layout/utilities",
      "parent": "/_layout",
      "children": [
        "/_layout/utilities/_layout",
        "/_layout/utilities/"
      ]
    },
    "/_layout/utilities/_layout": {
      "filePath": "_layout/utilities/_layout.tsx",
      "parent": "/_layout/utilities",
      "children": [
        "/_layout/utilities/_layout/planck-convertor"
      ]
    },
    "/_layout/utilities/": {
      "filePath": "_layout/utilities/index.tsx",
      "parent": "/_layout/utilities"
    },
    "/_layout/utilities/_layout/planck-convertor": {
      "filePath": "_layout/utilities/_layout/planck-convertor.tsx",
      "parent": "/_layout/utilities/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
