version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    command: '/app/scripts/docker/local-run.sh'
    ports:
      - '8080:8080'
      - '9229:9229'
    env_file: .env.local
    volumes:
      - './src:/app/src'
