import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WalletStoreProvider } from "@/providers/walletStoreProvider";
import { PolkadotWalletsContextProvider } from "@/providers/polkadotWalletsContextProvider.client";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Polka Dapp",
  description: "Generated by create polka app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PolkadotWalletsContextProvider>
        <body className={inter.className}>
          <WalletStoreProvider>
            <Header />
            {children}
          </WalletStoreProvider>
        </body>
      </PolkadotWalletsContextProvider>
    </html>
  );
}
