[package]
name = "ytpurchase"
version = "0.1.0"
authors = ["Daryl"]
edition = "2021"

[dependencies]
ink = { version = "5.0.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3.3.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "5.0.0",  default-features = false }

[lib]
name = "ytpurchase"
path = "lib.rs"

[features]
default = ["std"]
std = ["ink/std", "scale/std", "scale-info/std"]
ink-as-dependency = []

[build]
target = "wasm32-unknown-unknown"
