module.exports = class Data1696461774261 {
    name = 'Data1696461774261'

    async up(db) {
        await db.query(`CREATE TABLE "impl_build" ("id" character varying NOT NULL, "impl_id" integer NOT NULL, "version" integer NOT NULL, "magic_bytes" text, "status" character varying(12) NOT NULL, "online_workers_count" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "ref_impl_id" character varying, CONSTRAINT "PK_5a7367725014a952d56efb311d2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_750a479d34edb9687e66ad0bb2" ON "impl_build" ("ref_impl_id") `)
        await db.query(`CREATE TABLE "pool_workers" ("id" character varying NOT NULL, "pool_id" integer NOT NULL, "worker_address" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "ref_pool_id" character varying, "ref_worker_id" character varying, CONSTRAINT "PK_1e1e55d91deabf4a8d10e73b7e0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_49e26e2c25129c25f8d2687364" ON "pool_workers" ("ref_pool_id") `)
        await db.query(`CREATE INDEX "IDX_fede968645623ef8ed64c06e0c" ON "pool_workers" ("ref_worker_id") `)
        await db.query(`CREATE TABLE "job_policy" ("id" character varying NOT NULL, "policy_id" integer NOT NULL, "pool_id" integer NOT NULL, "enabled" boolean NOT NULL, "applicable_scope" character varying(9) NOT NULL, "start_block" integer, "end_block" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "ref_pool_id" character varying, CONSTRAINT "PK_a24e37e2bc776c5b9ef3b832103" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d5e2e034dba98b6a4128dfc531" ON "job_policy" ("ref_pool_id") `)
        await db.query(`CREATE TABLE "job_event" ("id" character varying NOT NULL, "sequence" integer NOT NULL, "kind" character varying(10) NOT NULL, "payload" jsonb, "block_number" integer NOT NULL, "block_time" TIMESTAMP WITH TIME ZONE NOT NULL, "ref_job_id" character varying, CONSTRAINT "PK_d4439f70bd53ce8a8a2a9a783c7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ddf07491f507f71fa65200b75a" ON "job_event" ("ref_job_id") `)
        await db.query(`CREATE TABLE "job" ("id" character varying NOT NULL, "job_id" integer NOT NULL, "unique_track_id" text, "pool_id" integer NOT NULL, "policy_id" integer NOT NULL, "depositor_address" text NOT NULL, "beneficiary_address" text NOT NULL, "assignee_address" text, "impl_build_version" integer, "destroyer_address" text, "status" character varying(10) NOT NULL, "result" character varying(7), "impl_spec_version" integer NOT NULL, "input" text, "output" text, "proof" text, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE, "processing_at" TIMESTAMP WITH TIME ZONE, "ended_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "ref_pool_id" character varying, "ref_policy_id" character varying, "ref_depositor_id" character varying, "ref_beneficiary_id" character varying, "ref_assignee_id" character varying, "ref_destroyer_id" character varying, CONSTRAINT "PK_98ab1c14ff8d1cf80d18703b92f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_25526336589e1d6f5b5d9c5b74" ON "job" ("job_id") `)
        await db.query(`CREATE INDEX "IDX_d89186683bb9bc65ad599e1485" ON "job" ("unique_track_id") `)
        await db.query(`CREATE INDEX "IDX_7e3ff2d82314f5deac2a85c303" ON "job" ("ref_pool_id") `)
        await db.query(`CREATE INDEX "IDX_2161bf3eeb6f82ff1c2441474f" ON "job" ("ref_policy_id") `)
        await db.query(`CREATE INDEX "IDX_7b55e9c278d79731d07102be51" ON "job" ("ref_depositor_id") `)
        await db.query(`CREATE INDEX "IDX_276a01ee81f849689f08074dc2" ON "job" ("ref_beneficiary_id") `)
        await db.query(`CREATE INDEX "IDX_0600c5b6fd9d4eafca86fd9152" ON "job" ("ref_assignee_id") `)
        await db.query(`CREATE INDEX "IDX_70813820e035f9d5684b9829eb" ON "job" ("ref_destroyer_id") `)
        await db.query(`CREATE INDEX "IDX_bac37f13b06c08534012dc3607" ON "job" ("status") `)
        await db.query(`CREATE TABLE "pool" ("id" character varying NOT NULL, "pool_id" integer NOT NULL, "owner_address" text NOT NULL, "impl_id" integer NOT NULL, "job_scheduler" character varying(8) NOT NULL, "create_job_enabled" boolean NOT NULL, "auto_destroy_processed_job_enabled" boolean NOT NULL, "metadata" bytea, "workers_count" integer NOT NULL, "online_workers_count" integer NOT NULL, "pending_jobs_count" integer NOT NULL, "processing_jobs_count" integer NOT NULL, "processed_jobs_count" integer NOT NULL, "successful_jobs_count" integer NOT NULL, "failed_jobs_count" integer NOT NULL, "errored_jobs_count" integer NOT NULL, "panicky_jobs_count" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "ref_owner_id" character varying, "ref_impl_id" character varying, CONSTRAINT "PK_db1bfe411e1516c01120b85f8fe" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_65de84d939c66d1ba8d503ee26" ON "pool" ("ref_owner_id") `)
        await db.query(`CREATE INDEX "IDX_149c1c2d2b1835eb24c74f8d82" ON "pool" ("ref_impl_id") `)
        await db.query(`CREATE TABLE "impl" ("id" character varying NOT NULL, "impl_id" integer NOT NULL, "owner_address" text NOT NULL, "attestation_method" character varying(6) NOT NULL, "metadata" bytea, "online_workers_count" integer NOT NULL, "pools_count" integer NOT NULL, "jobs_count" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "ref_owner_id" character varying, CONSTRAINT "PK_a8cc1327d4d3bff68326b317e75" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_de0cb161dc07f81bda924ea616" ON "impl" ("ref_owner_id") `)
        await db.query(`CREATE TABLE "worker_event" ("id" character varying NOT NULL, "sequence" integer NOT NULL, "kind" character varying(20) NOT NULL, "payload" jsonb, "block_number" integer NOT NULL, "block_time" TIMESTAMP WITH TIME ZONE NOT NULL, "ref_worker_id" character varying, CONSTRAINT "PK_10a145337603818a534cffc34d6" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7c6fa85b6a6dfcfd632f98ed2a" ON "worker_event" ("ref_worker_id") `)
        await db.query(`CREATE TABLE "worker" ("id" character varying NOT NULL, "address" text NOT NULL, "owner_address" text NOT NULL, "impl_id" integer NOT NULL, "impl_build_version" integer, "status" character varying(17) NOT NULL, "impl_spec_version" integer, "attestation_method" character varying(6), "attestation_expires_at" TIMESTAMP WITH TIME ZONE, "last_attested_at" TIMESTAMP WITH TIME ZONE, "last_heartbeat_received_at" TIMESTAMP WITH TIME ZONE, "offline_at" TIMESTAMP WITH TIME ZONE, "offline_reason" character varying(24), "uptime_started_at" TIMESTAMP WITH TIME ZONE, "uptime" integer, "pools_count" integer NOT NULL, "pending_jobs_count" integer NOT NULL, "processing_jobs_count" integer NOT NULL, "processed_jobs_count" integer NOT NULL, "successful_jobs_count" integer NOT NULL, "failed_jobs_count" integer NOT NULL, "errored_jobs_count" integer NOT NULL, "panicky_jobs_count" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, "ref_owner_id" character varying, "ref_impl_id" character varying, "ref_impl_build_id" character varying, CONSTRAINT "PK_dc8175fa0e34ce7a39e4ec73b94" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_18cd58bc8d6028b24a7539e559" ON "worker" ("address") `)
        await db.query(`CREATE INDEX "IDX_2b8766ef5a90db3f499f1d2d47" ON "worker" ("ref_owner_id") `)
        await db.query(`CREATE INDEX "IDX_9873d8ac4278e50cc60ca3642c" ON "worker" ("ref_impl_id") `)
        await db.query(`CREATE INDEX "IDX_2d5cac8fb860281df96d750ded" ON "worker" ("ref_impl_build_id") `)
        await db.query(`CREATE INDEX "IDX_fdca7f90c98f110b79c5842108" ON "worker" ("status") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, "workers_count" integer NOT NULL, "pools_count" integer NOT NULL, "created_jobs_count" integer NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "impl_build" ADD CONSTRAINT "FK_750a479d34edb9687e66ad0bb24" FOREIGN KEY ("ref_impl_id") REFERENCES "impl"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_workers" ADD CONSTRAINT "FK_49e26e2c25129c25f8d2687364b" FOREIGN KEY ("ref_pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool_workers" ADD CONSTRAINT "FK_fede968645623ef8ed64c06e0c1" FOREIGN KEY ("ref_worker_id") REFERENCES "worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "job_policy" ADD CONSTRAINT "FK_d5e2e034dba98b6a4128dfc5318" FOREIGN KEY ("ref_pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "job_event" ADD CONSTRAINT "FK_ddf07491f507f71fa65200b75a4" FOREIGN KEY ("ref_job_id") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_7e3ff2d82314f5deac2a85c303f" FOREIGN KEY ("ref_pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_2161bf3eeb6f82ff1c2441474f5" FOREIGN KEY ("ref_policy_id") REFERENCES "job_policy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_7b55e9c278d79731d07102be51a" FOREIGN KEY ("ref_depositor_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_276a01ee81f849689f08074dc20" FOREIGN KEY ("ref_beneficiary_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_0600c5b6fd9d4eafca86fd91520" FOREIGN KEY ("ref_assignee_id") REFERENCES "worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_70813820e035f9d5684b9829ebd" FOREIGN KEY ("ref_destroyer_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_65de84d939c66d1ba8d503ee265" FOREIGN KEY ("ref_owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_149c1c2d2b1835eb24c74f8d826" FOREIGN KEY ("ref_impl_id") REFERENCES "impl"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "impl" ADD CONSTRAINT "FK_de0cb161dc07f81bda924ea616e" FOREIGN KEY ("ref_owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker_event" ADD CONSTRAINT "FK_7c6fa85b6a6dfcfd632f98ed2ae" FOREIGN KEY ("ref_worker_id") REFERENCES "worker"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_2b8766ef5a90db3f499f1d2d470" FOREIGN KEY ("ref_owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_9873d8ac4278e50cc60ca3642cb" FOREIGN KEY ("ref_impl_id") REFERENCES "impl"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "worker" ADD CONSTRAINT "FK_2d5cac8fb860281df96d750ded0" FOREIGN KEY ("ref_impl_build_id") REFERENCES "impl_build"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "impl_build"`)
        await db.query(`DROP INDEX "public"."IDX_750a479d34edb9687e66ad0bb2"`)
        await db.query(`DROP TABLE "pool_workers"`)
        await db.query(`DROP INDEX "public"."IDX_49e26e2c25129c25f8d2687364"`)
        await db.query(`DROP INDEX "public"."IDX_fede968645623ef8ed64c06e0c"`)
        await db.query(`DROP TABLE "job_policy"`)
        await db.query(`DROP INDEX "public"."IDX_d5e2e034dba98b6a4128dfc531"`)
        await db.query(`DROP TABLE "job_event"`)
        await db.query(`DROP INDEX "public"."IDX_ddf07491f507f71fa65200b75a"`)
        await db.query(`DROP TABLE "job"`)
        await db.query(`DROP INDEX "public"."IDX_25526336589e1d6f5b5d9c5b74"`)
        await db.query(`DROP INDEX "public"."IDX_d89186683bb9bc65ad599e1485"`)
        await db.query(`DROP INDEX "public"."IDX_7e3ff2d82314f5deac2a85c303"`)
        await db.query(`DROP INDEX "public"."IDX_2161bf3eeb6f82ff1c2441474f"`)
        await db.query(`DROP INDEX "public"."IDX_7b55e9c278d79731d07102be51"`)
        await db.query(`DROP INDEX "public"."IDX_276a01ee81f849689f08074dc2"`)
        await db.query(`DROP INDEX "public"."IDX_0600c5b6fd9d4eafca86fd9152"`)
        await db.query(`DROP INDEX "public"."IDX_70813820e035f9d5684b9829eb"`)
        await db.query(`DROP INDEX "public"."IDX_bac37f13b06c08534012dc3607"`)
        await db.query(`DROP TABLE "pool"`)
        await db.query(`DROP INDEX "public"."IDX_65de84d939c66d1ba8d503ee26"`)
        await db.query(`DROP INDEX "public"."IDX_149c1c2d2b1835eb24c74f8d82"`)
        await db.query(`DROP TABLE "impl"`)
        await db.query(`DROP INDEX "public"."IDX_de0cb161dc07f81bda924ea616"`)
        await db.query(`DROP TABLE "worker_event"`)
        await db.query(`DROP INDEX "public"."IDX_7c6fa85b6a6dfcfd632f98ed2a"`)
        await db.query(`DROP TABLE "worker"`)
        await db.query(`DROP INDEX "public"."IDX_18cd58bc8d6028b24a7539e559"`)
        await db.query(`DROP INDEX "public"."IDX_2b8766ef5a90db3f499f1d2d47"`)
        await db.query(`DROP INDEX "public"."IDX_9873d8ac4278e50cc60ca3642c"`)
        await db.query(`DROP INDEX "public"."IDX_2d5cac8fb860281df96d750ded"`)
        await db.query(`DROP INDEX "public"."IDX_fdca7f90c98f110b79c5842108"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`ALTER TABLE "impl_build" DROP CONSTRAINT "FK_750a479d34edb9687e66ad0bb24"`)
        await db.query(`ALTER TABLE "pool_workers" DROP CONSTRAINT "FK_49e26e2c25129c25f8d2687364b"`)
        await db.query(`ALTER TABLE "pool_workers" DROP CONSTRAINT "FK_fede968645623ef8ed64c06e0c1"`)
        await db.query(`ALTER TABLE "job_policy" DROP CONSTRAINT "FK_d5e2e034dba98b6a4128dfc5318"`)
        await db.query(`ALTER TABLE "job_event" DROP CONSTRAINT "FK_ddf07491f507f71fa65200b75a4"`)
        await db.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_7e3ff2d82314f5deac2a85c303f"`)
        await db.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_2161bf3eeb6f82ff1c2441474f5"`)
        await db.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_7b55e9c278d79731d07102be51a"`)
        await db.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_276a01ee81f849689f08074dc20"`)
        await db.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_0600c5b6fd9d4eafca86fd91520"`)
        await db.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_70813820e035f9d5684b9829ebd"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_65de84d939c66d1ba8d503ee265"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_149c1c2d2b1835eb24c74f8d826"`)
        await db.query(`ALTER TABLE "impl" DROP CONSTRAINT "FK_de0cb161dc07f81bda924ea616e"`)
        await db.query(`ALTER TABLE "worker_event" DROP CONSTRAINT "FK_7c6fa85b6a6dfcfd632f98ed2ae"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_2b8766ef5a90db3f499f1d2d470"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_9873d8ac4278e50cc60ca3642cb"`)
        await db.query(`ALTER TABLE "worker" DROP CONSTRAINT "FK_2d5cac8fb860281df96d750ded0"`)
    }
}
