name: "Marketplace Backend"
mode: "debug"
port: 6465
version: "v1.0.0"

contracts:
  BASE_SEPOLIA:
    RPC: "wss://base-sepolia.g.alchemy.com/v2/_j5REyXi-XySkwLHp790Wvs9kBbxhUba"
    Marketplace:
      address: "0xC6B5c98FD8A8C9d8aa2B0f79a66EC55b0D2dad69"
      start_at: 14271894
      query_history: true
      query_interval: 200000
    Application:
      address: "0xf628B6024af73D0f29c251e0fB306e5f8bA6FcFA"
      start_at: 14271602
      query_history: true
      query_interval: 200000

postgres:
  host: "127.0.0.1"
  port: "5432"
  user: ""
  password: ""
  dbname: "marketplace"
  schema: "public"
  max_open_conns: 200
  max_idle_conns: 50
