[package]
name = "substk-client-kv-store-service"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
chrono = "0.4.38"
jsonwebtoken = { version = "9.3.0" }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { version = "0.7.7", features = ["macros", "default"] }
clap = { workspace = true }
codec = { workspace = true, features = ["derive"] }
const-hex = "1.13.1"
forwarded-header-value = { workspace = true }
futures = { workspace = true }
hex-literal = "0.4.1"
http = { workspace = true }
http-body-util = { workspace = true }
hyper = "1.3"
jsonrpsee = { workspace = true, features = ["full"] }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
primitive-types = "0.12.2"
serde = { workspace = true }
serde_json = { workspace = true, default-features = true }
thiserror = { workspace = true }
tokio = { features = ["time", "sync"], workspace = true, default-features = true }
tower = { workspace = true, features = ["util"] }
tower-http = { workspace = true, features = ["cors"] }

sc-client-api = { workspace = true, default-features = true }
sc-service = { workspace = true, default-features = true }
#sc-informant = { workspace = true, default-features = true }
#sc-network = { workspace = true, default-features = true }
#sc-rpc = { workspace = true, default-features = true }
#sc-rpc-server = { workspace = true, default-features = true }
#sc-service = { workspace = true, default-features = true }
scale-decode = { version = "0.13.1", features = ["derive"] }
sp-api = { workspace = true, default-features = true }
#sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-keyring = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
subxt = { version = "0.37.0", features = [] }

substk-client-kv-store = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
tempfile = { workspace = true }
