[package]
name = "pfx-pallet-mq-runtime-api"
version = "0.1.0"
edition = "2021"

[dependencies]
sp-api = { workspace = true }
pfx-mq = { workspace = true }


[features]
default = ["std"]
std = [
	"sp-api/std",
]
