# https://pre-commit.com

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: forbid-submodules
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.17
    hooks:
      - id: typos
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Format files
        entry: cargo +nightly fmt
        language: system
        types: [rust]
        args: ["--all", "--", "--check"]
      - id: clippy
        name: clippy
        description: Run linter
        entry: cargo clippy
        language: system
        types: [rust]
        args: ["--all-targets", "--", "-D", "warnings"]
        pass_filenames: false
