# list all cmds
default:
    just --list --unsorted

fmt:
    cargo +nightly fmt
    taplo fmt

check:
    cargo check --release

clippy:
    cargo clippy --release

build *args:
    cargo build -p solochain-template-node --release {{args}}

# only build runtime
build-runtime *args:
    cargo build -p solochain-template-runtime --release {{args}}

test *args:
    cargo test {{args}} -- --include-ignored --nocapture