import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.scss";
import "@rainbow-me/rainbowkit/styles.css";

//components
import Header from "@/components/Header";
import PageTransition from "@/components/transition/PageTransition";
import StairTransition from "@/components/transition/StairTransition";
import { Providers } from "./providers";

const inter = Inter({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700"],
	variable: "--font-Inter",
});

export const metadata: Metadata = {
	title: "Melody",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html>
			<body className={inter.variable}>
				<Providers>
					<Header />
					<StairTransition />
					<PageTransition>{children}</PageTransition>
				</Providers>
			</body>
		</html>
	);
}
