[profile.default]
src = "contracts"
out = "out"
libs = ["dependencies"]
auto_detect_remappings = true

[dependencies]
forge-std = { version = "1.9.1" }
"@openzeppelin-contracts" = { version = "5.0.2" }
"@openzeppelin-contracts-upgradeable" = { version = "5.0.2" }

[rpc_endpoints]
dev = "${DEV_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
bnb = "${BNB_RPC_URL}"
bnb_testnet = "${BNB_TESTNET_RPC_URL}"