export const Ourmenu = [
    {
        id:'coffee1',
        imgUrl:'/image/coffee1.webp',
        title:'Mocha',
        price:'$5'
    },
    {
        id:'coffee2',
        imgUrl:'/image/coffee2.webp',
        title:'Espresso',
        price:'$5'
    },
    {
        id:'coffee3',
        imgUrl:'/image/coffee3.webp',
        title:'Cappucino',
        price:'$6'
    },
    {
        id:'coffee4',
        imgUrl:'/image/coffee4.webp',
        title:'Black Coffee',
        price:'$4'
    },
    {
        id:'coffee5',
        imgUrl:'/image/coffee5.webp',
        title:'Americano',
        price:'$4'
    },
]

export const Desserts = [
    {
        id:'dessert1',
        imgUrl:'/image/dessert1.jpeg',
    },
    {
        id:'dessert2',
        imgUrl:'/image/dessert2.jpeg',
    },
    {
        id:'dessert3',
        imgUrl:'/image/dessert3.jpeg',
    },
    {
        id:'dessert4',
        imgUrl:'/image/dessert4.jpeg',
    },
    {
        id:'beverage1',
        imgUrl:'/image/beverage1.jpeg',
    },
    {
        id:'beverage2',
        imgUrl:'/image/beverage2.jpeg',
    },
    {
        id:'beverage3',
        imgUrl:'/image/beverage3.jpeg',
    },
    {
        id:'beverage4',
        imgUrl:'/image/beverage4.jpeg',
    },
]