[package]
name = "substk-client-kv-store"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0"
codec = { workspace = true, features = ["derive"] }
log = { workspace = true, default-features = true }
moka = { version = "0.12.8", features = ["sync"] }
parity-db = { workspace = true }
parking_lot = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
thiserror = "1.0"
tokio = { features = ["time"], workspace = true, default-features = true }

sc-client-api = { workspace = true, default-features = true }
sc-keystore = { workspace = true, default-features = true }
serde = { version = "1.0.210", features = ["derive"] }
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

[dev-dependencies]
env_logger = { workspace = true }
tempfile = { workspace = true }
