[package]
edition = "2021"
name = "pflix"
version = "0.3.2"
build = "build.rs"

[profile.release]
panic = "abort"

[dependencies]
anyhow = { version = "1" }
base64 = { version = "0.13", default-features = false, features = ["alloc"] }
clap = { version = "4.5", features = ["derive", "cargo"] }
const-str = { version = "0.5", features = ["proc"] }
hex_fmt = "0.3.0"
humantime = "2.1.0"
lazy_static = { version = "1.4.0", default-features = false }
num_cpus = "1.13"
parity-scale-codec = { version = "3.6.1", default-features = false }
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "socks",
    "blocking",
    "hickory-dns",
] }
serde_json = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
tracing = "0.1"
urlencoding = "2.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
tower = { version = "0.4", features = ["limit", "load-shed"] }
tonic = { version = "0.12" }
rustls-pki-types = { version = "=0.2.1", default-features = false, optional = true }
reqwest-env-proxy = { path = "../../../crates/reqwest-env-proxy" }
pfx-sanitized-logger = { path = "../../../crates/pfx-sanitized-logger" }
pfx = { path = "../../../crates/pfx" }
pfx-api = { path = "../../../crates/pfx/api", features = [
    "pflix-client",
] }
pfx-pal = { path = "../../../crates/pfx/pal" }
pfx-allocator = { path = "../../../crates/pfx-allocator" }
pfx-types = { path = "../../../crates/pfx-types", default-features = false, features = [
    "enable_serde",
    "full_crypto",
] }
sgx-api-lite = { path = "../../../crates/sgx-api-lite" }
sgx-attestation = { path = "../../../crates/sgx-attestation", features = ["report"] }

[build-dependencies]
vergen = { version = "8.3", features = ["build", "git", "gitcl"] }


[patch.crates-io]
ring = { git = "https://github.com/jasl/ring-xous", branch = "better-wasm32-support" }


[features]
only-attestation = ["pfx/only-attestation", "pfx-api/only-attestation"]
verify-pflixbin = ["pfx/verify-pflixbin", "pfx-api/verify-pflixbin"]
