//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::assets_issues::Entity as AssetsIssues;
pub use super::assets_nfts::Entity as AssetsNfts;
pub use super::pfxassets::Entity as Pfxassets;
pub use super::wallets::Entity as Wallets;
