[toolchain]
# Stable
#channel = "1.69.0" # rustc 1.69.0 (84c898d65 2023-04-16)
# Nightly
channel = "nightly-2024-01-05" # rustc 1.77.0-nightly (595bc6f00 2024-01-05)
components = ["rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
