[package]
name = "pallet-evm-precompile-call-hybrid-vm"
version = "0.4.0"
description = "Call Hybrid vm precompiles for EVM pallet."
repository.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
evm = { workspace = true, default-features = false, features = ["with-codec"] }

# Substrate
sp-core = { workspace = true, default-features = false}
sp-io = { workspace = true, default-features = false}
sp-std = { workspace = true, default-features = false}
sp-runtime = { workspace = true, default-features = false}
frame-support = { workspace = true, default-features = false}
frame-system = { workspace = true, default-features = false}

# frontier
pallet-evm = { workspace = true, default-features = false}
fp-evm = { workspace = true, default-features = false}

hp-system = { workspace = true, default-features = false }
pallet-hybrid-vm = { workspace = true, default-features = false }

[dev-dependencies]
frame-system = { workspace = true, default-features = false}
pallet-balances = { workspace = true, default-features = false}
pallet-timestamp = { workspace = true, default-features = false}

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-io/std",
	"frame-support/std",
	"frame-system/std",	
	"pallet-evm/std",
	"fp-evm/std",
	"evm/std",
	"pallet-evm/std",
	"pallet-hybrid-vm/std",
]

runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"pallet-evm/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"pallet-evm/try-runtime",
]