[package]
name = "pfx-api"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
frame-system = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-core = { workspace = true, features = ["full_crypto"] }
sp-application-crypto = { workspace = true, features = ["full_crypto"] }
sp-runtime = { workspace = true }
parity-scale-codec   = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
base64 = { workspace = true }
derive_more = { workspace = true, features = ["from_str"] }
prost = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true, optional = true }
log = { workspace = true }
primitive-types = { workspace = true, optional = true }
im = { workspace = true }
tonic = { workspace = true }

pfx-trie-storage = { workspace = true, features = ["serde"] }
pfx-types = { workspace = true, features = ["enable_serde", "full_crypto"] }
pfx-crypto = { workspace = true }
chain = { workspace = true }
pfx-mq = { workspace = true }


[dev-dependencies]
insta = "1.13.0"
hex = "0.4.3"


[build-dependencies]
tonic-build = { workspace = true, features = ["prost"] }


[features]
default = ["std"]

std = [
    "derive_serde",
    "sp-core/full_crypto",
    "sp-runtime/std",
    "sp-application-crypto/std",
    "frame-system/std",
    "chain/std",
]

sgx = []
pflix-client = [
    "anyhow",
]

derive_serde = [
    "pfx-trie-storage/serde",
    "primitive-types/serde",
]

only-attestation = [
	"chain/only-attestation"
]
verify-pflixbin = [
	"chain/verify-pflixbin"
]