[package]
name = "pallet-currencies"
description = "Provide `MultiCurrency` implementation using `pallet-balances` and `orml-tokens` module."
repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/currencies"
license = "Apache-2.0"
version = "0.4.1-dev"
authors = ["Laminar Developers <hello@laminar.one>", "Sora Yu <ymlll0508@gmail.com>"]
edition = "2021"

[dependencies]
scale-codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.149", default-features = false, optional = true, features = ["derive", "alloc"] }

frame-support = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }
frame-system = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }
sp-core = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }
sp-io = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }
sp-std = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }

orml-traits = { workspace = true }
orml-tokens = { workspace = true }
orml-utilities = { workspace = true }

primitives = { path = "../../primitives", default-features = false }

[dev-dependencies]
hex = { version = "0.4",  features = ["std"] }
hex-literal = { version = "0.3.1" }
pallet-assets = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }
serde_json = { version = "1.0.89", default-features = false, features = ["alloc"]}
sp-core = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-v1.9.0" }


[features]
default = ["std"]
std = [
	"serde",
	"frame-support/std",
	"frame-system/std",
	"primitives/std",
	"orml-tokens/std",
	"orml-traits/std",
	"orml-utilities/std",
	"pallet-assets/std",
	"scale-codec/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"orml-traits/std",
	"orml-tokens/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
]
