version: "3"

services:
  redis:
    image: redis:7-alpine
    container_name: subsquid_redis
    ports:
      - "${REDIS_PORT}:6379"
  db:
    image: postgres:15
    container_name: subsquid_db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    ports:
      - "${DB_PORT}:5432"
#    command: ["postgres", "-c", "log_statement=all"]
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

#    cockroach:
#      image: cockroachdb/cockroach:v21.2.9
#      ports:
#        - "${DB_PORT}:26257"
#      command: [
#        "start-single-node",
#        "--insecure"
#      ]
