import { HexString } from '@gear-js/api';
export declare const H160: (value: HexString | Uint8Array) => `0x${string}` | Uint8Array;
export declare const H256: (value: HexString | Uint8Array) => `0x${string}` | Uint8Array;
export declare const ActorId: (value: HexString | Uint8Array) => `0x${string}` | Uint8Array;
export declare const CodeId: (value: HexString | Uint8Array) => `0x${string}` | Uint8Array;
export declare const MessageId: (value: HexString | Uint8Array) => `0x${string}` | Uint8Array;
export type H160 = HexString | Uint8Array;
export type H256 = HexString | Uint8Array;
export type ActorId = HexString | Uint8Array;
export type CodeId = HexString | Uint8Array;
export type MessageId = HexString | Uint8Array;
