[package]
name = "cache_protocol"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[dependencies]
ink = { version = "4.2.1", default-features = false }
ink_env = { version = "4.2.1", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.6", default-features = false, features = ["derive"], optional = true }

hex = { version = "0.4.3", default-features = false }

# OpenBrush dependency
# openbrush = { git = "https://github.com/Brushfam/openbrush-contracts", branch = "main", default-features = false, features=["psp34"] }

cache_token = { path = "/home/cess/work/cache_token", default-features = false, features = ["ink-as-dependency"]}

[dev-dependencies]
ink_e2e = "4.2.1"

[lib]
name = "cache_protocol"
path = "lib.rs"

[features]
default = ["std"]
std = [
    "cache_token/std",
    "hex/std",
    "ink/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
e2e-tests = []
