services:
  validator:
    image: validator
    build:
      context: .
      dockerfile: Dockerfile.validator
    healthcheck:
      # To see healthcheck output:
      # docker inspect --format "{{json .State.Health }}" docker-validator-1 | jq
      test: [ "CMD", "curl", "-s", "-f", "http://127.0.0.1:26657/health" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    # uncomment to provide amount of sequencers to provision (default: 1)
    # command: [ "/opt/entrypoint.sh", "2" ]
    volumes:
      - credentials:/credentials
      - genesis:/genesis

  sequencer-0:
    image: bridge
    build:
      context: .
      dockerfile: Dockerfile.bridge
    depends_on:
      - validator
    healthcheck:
      # To see healthcheck output:
      # docker inspect --format "{{json .State.Health }}" docker-sequencer-0-1 | jq
      test: [ "CMD", "/opt/bridge-healthcheck.sh", "/credentials/bridge-0.jwt" ]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 10s
    # uncomment to provide the id of the sequencer (default: 0)
    # command: ["/opt/entrypoint.sh", "0"]
    ports:
      - 26658:26658
    volumes:
      - credentials:/credentials:consistent
      - genesis:/genesis

volumes:
  # local volume where sequencer's credentials can persist
  credentials:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./credentials"
  # a temporary fs where the genesis hash is announced
  genesis:
    driver_opts:
      type: tmpfs
      device: tmpfs
