[advisories]
version = 2
yanked = "warn"
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
  # wait for libp2p to update
  "RUSTSEC-2024-0344",
]

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[licenses]
version = 2
confidence-threshold = 0.8

allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "0BSD",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Unlicense",
    "MPL-2.0",
    # https://github.com/briansmith/ring/issues/902
    "LicenseRef-ring",
]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
