[package]
name = "sp1eip712"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
sp1-zkvm = { workspace = true }
sp1-lib = { workspace = true }

tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2", features = [
  "keccak",
] }

# secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", branch = "patch-secp256k1-v0.29.0", features = ["recovery"] }

zk-6358 = { path = "../../../zkp/zk-6358" }
sp1-eip712-type = { path = "../sp1-eip712-type" }
pc-lib ={ path = "../pc-lib"}

anyhow = { version = "1.0.86" }

cfg-if = "1.0"

[target.'cfg(all(target_os = "zkvm", target_vendor = "succinct"))'.dependencies]
ecdsa-core = { git = "https://github.com/sp1-patches/signatures", package = "ecdsa", branch = "patch-ecdsa-v0.16.9", features = ["verifying", "alloc"] }
# k256
k256 = { version = "0.13.3", features = [
  "ecdsa",
  "std",
  "bits",
]}

[dev-dependencies]
rand = { version = "0.8.5" }
itertools = { version = "0.13.0" }
num = { version = "0.4.3" }