[da]
# Connection string for SQL database to have stored blocks, for example"
#  - "sqlite://demo_data/da.sqlite?mode=rwc"
#  - "sqlite::memory:"
#  - "postgresql://root:hunter2@aws.amazon.com/mock-da"
connection_string = "sqlite://mock_da.sqlite?mode=rwc"
# String representation of sequencer address.
# For initial full node should match genesis of sequencer-registry.
# It is going to be a DA address that blobs from this node will be associated.
sender_address = "0000000000000000000000000000000000000000000000000000000000000000"
# Defines how new blocks should be produced.
# Can be 2 options:
#  - periodic: new blocks produced periodically every `block_time_ms`.
#              Empty blocks can be produced with this option.
#  - on_submit: new blocks are produced on submission of batch/blob.
#              `block_time_ms` defines maximum waiting time for a new block
block_producing = "periodic"
# Block time depends on `block_producing`:
# For `periodic` it defines how often new blocks will be produced, approximately.
# For `on_submit` it defines max time service will wait for a new block.
block_time_ms = 3_000

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "../../rollup-starter-data"

# We define the rollup's genesis to occur at block number `start_height`. The rollup will ignore
# any blocks before this height
[runner]
genesis_height = 0
da_polling_interval_ms = 1000

[runner.rpc_config]
bind_host = "127.0.0.1"
bind_port = 12345
[runner.axum_config]
bind_host = "127.0.0.1"
bind_port = 12346

[proof_manager]
aggregated_proof_block_jump = 1
prover_address = "sov1pv9skzctpv9skzctpv9skzctpv9skzctpv9skzctpv9skzctpv9stup8tx"
