[package]
name = "pallet-offchain_computing-pool-primitives"
version = "0.0.1-dev"
description = "A crate that hosts a common definitions that are relevant for the pallet-offchain_computing."
authors.workspace = true
repository.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
edition = "2021"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
scale-codec = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }

sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

base-primitives = { package = "pallet-offchain_computing-infra-primitives", path = "../../offchain_computing_infra/primitives", default-features = false }

[features]
default = ["std"]
std = [
	"scale-codec/std",
	"scale-info/std",
	"sp-core/std",
	"base-primitives/std",
]
