[package]
name = "sigmaverse"
version = "0.1.0"
edition = "2021"

[dependencies]
sigmaverse-gamestate = { path = "../gamestate" }
vnft-service = { path = "../vnft-service" }
gstd.workspace = true
sails-rs.workspace = true

[build-dependencies]
sails-rs = { workspace = true, features = ["wasm-builder"] }

[dev-dependencies]
futures.workspace = true
gclient.workspace = true
gtest.workspace = true
sigmaverse-client = { path = "../client" }
tokio = { workspace = true, features = ["rt", "macros"] }