- name: create genesis folder
  file:
    path: /home/sovereign/genesis
    state: directory
    owner: sovereign
    group: sovereign
  become: true
  become_user: root

- name: synchronize genesis folder to remote
  ansible.builtin.synchronize:
    src: "{{ role_path }}/files/genesis/"
    dest: "{{ genesis_folder }}"
    delete: no
    recursive: yes
  become: true
  become_user: sovereign

- name: render sequencer config with address
  become: true
  become_user: sovereign
  ansible.builtin.template:
    src: "genesis/sequencer_registry.json.j2"
    dest: "{{genesis_folder}}/sequencer_registry.json"
  vars:
    sequencer_da_address: "{{ sequencer_genesis_address }}"

- name: render chain state config with genesis height
  become: true
  become_user: sovereign
  ansible.builtin.template:
    src: "chain_state.json.j2"
    dest: "{{genesis_folder}}/chain_state.json"
  vars:
    genesis_da_height: "{{ rollup_da_start_height }}"