- name: checkout repo to home folder
  become: true
  become_user: ubuntu
  git:
    repo: "git@github.com:/{{ rollup_org_name }}/{{ rollup_repo_name }}.git"
    dest: "/home/ubuntu/{{ rollup_repo_dir }}"
    version: "{{ rollup_commit_hash }}"
    accept_hostkey: yes
    force: yes
