[package]
name = "sov-modules-rollup-blueprint"
description = "This crate contains abstractions needed to create a new rollup"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
readme = "README.md"
resolver = "2"
publish = true

[lints]
workspace = true

[dependencies]
derivative = { workspace = true, optional = true }
sov-rollup-interface = { workspace = true, features = ["native"] }
sov-stf-runner = { workspace = true, features = ["native"], optional = true }
sov-state = { workspace = true }
sov-modules-api = { workspace = true, features = ["native"] }
sov-cli = { workspace = true, optional = true }
sov-modules-stf-blueprint = { workspace = true, features = ["native"] }
sov-db = { workspace = true, optional = true }
sov-sequencer = { workspace = true, optional = true }
sov-sequencer-registry = { workspace = true }
sov-ledger-apis = { workspace = true, optional = true }

anyhow = { workspace = true }
async-trait = { workspace = true, optional = true }
tower-http = { workspace = true, features = ["trace", "compression-gzip", "propagate-header", "set-header", "cors"], optional = true }
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, features = ["sync"], optional = true }

[features]
default = ["native"]
native = [
    "async-trait",
    "derivative",
    "serde_json",
    "sov-cli",
    "sov-db",
    "sov-ledger-apis",
    "sov-modules-api/native",
    "sov-modules-stf-blueprint/native",
    "sov-rollup-interface/native",
    "sov-sequencer",
    "sov-state/native",
    "sov-stf-runner",
    "sov-stf-runner?/native",
    "tokio",
    "tower-http",
    "sov-sequencer-registry/native"
]
