// Generated by dedot cli

import type { GenericSubstrateApi } from "dedot/types";
import type {
  GenericContractTx,
  GenericContractTxCall,
  ContractTxOptions,
  ContractSubmittableExtrinsic,
} from "dedot/contracts";

export interface ContractTx<ChainApi extends GenericSubstrateApi>
  extends GenericContractTx<ChainApi> {
  /**
   * A message that can be called on instantiated contracts.
   * This one flips the value of the stored `bool` from `true`
   * to `false` and vice versa.
   *
   * @param {ContractTxOptions} options
   *
   * @selector 0x633aa551
   **/
  flip: GenericContractTxCall<
    ChainApi,
    (options: ContractTxOptions) => ContractSubmittableExtrinsic<ChainApi>
  >;
}
