[package]
name = "cybros-origin-runtime"
version = "0.0.1-dev"
description = "Cybros Origin runtime"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition = "2021"
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = { version = "0.4.20", default-features = false }
static_assertions = { version = "1.1.0" }

scale-codec = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive", "serde"] }
serde_json = { version = "1.0.108", default-features = false, features = ["alloc"] }

sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false, features = ["serde"] }
sp-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false, features = ["serde"] }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false, features = ["serde"] }
sp-genesis-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false, features = ["serde"] }
sp-session = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-storage = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false, features = ["serde"] }

frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
frame-executive = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
frame-try-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false, optional = true }

frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false, optional = true }
pallet-timestamp = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-insecure-randomness-collective-flip = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

pallet-aura = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

pallet-transaction-payment = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-skip-feeless-payment = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-proxy = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-assets = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-vesting = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

pallet-tx-pause = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-safe-mode = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

pallet-treasury = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-identity = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }

pallet-contracts = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", default-features = false }
pallet-offchain_computing-infra = { path = "../../pallets/offchain_computing_infra", default-features = false }
pallet-offchain_computing-pool = { path = "../../pallets/offchain_computing_pool", default-features = false }

# Local Dependencies
runtime-primitives = { package = "cybros-runtime-primitives", path = "../../runtime-primitives", default-features = false }

[dev-dependencies]
keyring = { package = "sp-keyring", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
separator = "0.4.1"

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master", optional = true }

[features]
default = ["std"]
std = [
	"log/std",
	"runtime-primitives/std",
	"scale-codec/std",
	"scale-info/std",
	"serde_json/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-consensus-grandpa/std",
	"sp-core/std",
	"sp-genesis-builder/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-storage/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"substrate-wasm-builder",
	"frame-benchmarking/std",
	"frame-executive/std",
	"frame-support/std",
	"frame-try-runtime?/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system-benchmarking?/std",
	"pallet-timestamp/std",
	"pallet-insecure-randomness-collective-flip/std",
	"pallet-aura/std",
	"pallet-grandpa/std",
	"pallet-utility/std",
	"pallet-multisig/std",
	"pallet-proxy/std",
	"pallet-balances/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-skip-feeless-payment/std",
	"pallet-vesting/std",
	"pallet-assets/std",
	"pallet-treasury/std",
	"pallet-identity/std",
	"pallet-tx-pause/std",
	"pallet-safe-mode/std",
	"pallet-sudo/std",
	"pallet-contracts/std",
	"pallet-offchain_computing-infra/std",
	"pallet-offchain_computing-pool/std",
]
runtime-benchmarks = [
	"sp-runtime/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"frame-system-benchmarking/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
	"pallet-grandpa/runtime-benchmarks",
	"pallet-utility/runtime-benchmarks",
	"pallet-multisig/runtime-benchmarks",
	"pallet-proxy/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-skip-feeless-payment/runtime-benchmarks",
	"pallet-vesting/runtime-benchmarks",
	"pallet-assets/runtime-benchmarks",
	"pallet-treasury/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
	"pallet-tx-pause/runtime-benchmarks",
	"pallet-safe-mode/runtime-benchmarks",
	"pallet-sudo/runtime-benchmarks",
	"pallet-contracts/runtime-benchmarks",
	"pallet-offchain_computing-infra/runtime-benchmarks",
	"pallet-offchain_computing-pool/runtime-benchmarks",
]
try-runtime = [
	"frame-try-runtime/try-runtime",
	"frame-executive/try-runtime",
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"sp-runtime/try-runtime",
	"pallet-timestamp/try-runtime",
	"pallet-insecure-randomness-collective-flip/try-runtime",
	"pallet-aura/try-runtime",
	"pallet-grandpa/try-runtime",
	"pallet-utility/try-runtime",
	"pallet-multisig/try-runtime",
	"pallet-proxy/try-runtime",
	"pallet-balances/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"pallet-skip-feeless-payment/try-runtime",
	"pallet-vesting/try-runtime",
	"pallet-assets/try-runtime",
	"pallet-treasury/try-runtime",
	"pallet-identity/try-runtime",
	"pallet-tx-pause/try-runtime",
	"pallet-safe-mode/try-runtime",
	"pallet-sudo/try-runtime",
	"pallet-contracts/try-runtime",
	"pallet-offchain_computing-infra/try-runtime",
	"pallet-offchain_computing-pool/try-runtime",
]
experimental = [
	"frame-support/experimental",
	"frame-system/experimental",
	"pallet-aura/experimental",
]