[workspace]

[package]
name = "assets"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "assets-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

loco-rs = { version = "0.11.0" }
migration = { path = "migration" }

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
ciborium = "0.2"
tokio = { version = "1.33.0", default-features = false }
tokio-util = "0.7"
async-trait = "0.1.74"
tracing = "0.1.40"
chrono = "0.4"
validator = { version = "0.18" }
sea-orm = { version = "1.1.0", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }

axum = { version = "0.7", features = ["multipart"] }
include_dir = "0.7"
uuid = { version = "1.6.0", features = ["v4"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }

sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.1", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.1" }
sp-crypto-hashing = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.10.1" }
# parity-scale-codec = { version = "3.6" }
parity-bip39 = { version = "2.0.1", features = ["rand"] }
blake2b_simd = { version = "1" }
byteorder = { version = "1.3.2" }
bytestream = "0.4"
itertools = { version = "0.13" }
hex = { version = "0.4" }
axum_typed_multipart = "0.13.1"
tempfile = "3.13.0"
mime_guess = "2.0.5"
mime = "0.3.17"
lazy_static = "1.5.0"

[[bin]]
name = "assets-cli"
path = "src/bin/main.rs"
required-features = []

[[bin]]
name = "tool"
path = "src/bin/tool.rs"
required-features = []

[dev-dependencies]
serial_test = "3.1.1"
rstest = "0.21.0"
loco-rs = { version = "0.11.0", features = ["testing"] }
insta = { version = "1.34.0", features = ["redactions", "yaml", "filters"] }
