[package]
name = "sov-test-utils"
description = "A set of utils for testing the Sovereign SDK"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
resolver = "2"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
axum-server = { workspace = true }
borsh = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }

ethereum-types = { workspace = true }
ethers-core = { workspace = true }
ethers-contract = { workspace = true }

#demo-stf = { workspace = true, features = ["native"], optional = true }
#demo-stf = { path = "../crates/stf", default-features = false, version = "0.3",optional = true }
#demo-stf = { path = "../stf", default-features = false, version = "0.3" }
stf-starter = { workspace = true,optional = true }
sha2 = { workspace = true }
sov-rollup-interface = { workspace = true }
sov-modules-api = { workspace = true, features = ["native", "test-utils"] }
sov-modules-stf-blueprint = { workspace = true, features = ["native", "test-utils"] }
sov-stf-runner = { workspace = true }
sov-value-setter = { workspace = true, features = ["native"] }
sov-attester-incentives = { workspace = true, features = ["native"] }
sov-prover-incentives = { workspace = true, features = ["native"] }
sov-modules-rollup-blueprint = { workspace = true, features = ["native"] }
sov-bank = { workspace = true, features = ["native"] }
sov-kernels = { workspace = true, features = ["native"] }
sov-ledger-apis = { workspace = true }
sov-ledger-json-client = { workspace = true }
sov-sequencer-json-client = { workspace = true }
sov-capabilities = { workspace = true, features = ["native"] }
sov-sequencer = { workspace = true }
sov-sequencer-registry = { workspace = true, features = ["native"] }
sov-chain-state = { workspace = true, features = ["native"] }
sov-db = { workspace = true }
sov-state = { workspace = true }
sov-mock-da = { workspace = true, features = ["native"] }
sov-mock-zkvm = { workspace = true, features = ["native"] }
tempfile = { workspace = true }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
jsonrpsee = { workspace = true }
rockbound = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[features]
default = []
# Not every downstream user of this crate may want to / can use `demo-stf` as a
# dependency, so it's optional.
#demo-stf = ["dep:demo-stf"]
stf-starter = ["dep:stf-starter"]
arbitrary = [
	"ethereum-types/arbitrary",
	"sov-db/arbitrary",
	"sov-mock-zkvm/arbitrary",
	"sov-modules-api/arbitrary",
	"sov-rollup-interface/arbitrary",
	"sov-sequencer-registry/arbitrary",
	"sov-state/arbitrary",
	"rockbound/arbitrary"
]
