[package]
name = "erc20"
version = "5.0.0"
authors = ["Parity Technologies <admin@parity.io> and modified by HybridVM"]
edition = "2021"

[dependencies]
derive_more = { version = "0.99.17", features = ["from", "display"] }
ink_primitives = { version = "5.0.0", git = "https://github.com/paritytech/ink", default-features = false }
ink_metadata = { version = "5.0.0", git = "https://github.com/paritytech/ink", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "5.0.0", git = "https://github.com/paritytech/ink", default-features = false }
ink_storage = { version = "5.0.0", git = "https://github.com/paritytech/ink", default-features = false }
ink = { version = "5.0.0", git = "https://github.com/paritytech/ink", default-features = false }
ink_prelude = { version = "5.0.0", git = "https://github.com/paritytech/ink", default-features = false }
scale = { package = "parity-scale-codec", version = "3.6.4", default-features = false, features = ["derive"] }
scale-info = { version = "2.11", default-features = false, features = ["derive"], optional = true }
scale-encode = { version = "0.6", default-features = false }
scale-decode = { version = "0.11", default-features = false }
scale-type-resolver = { version = "0.1.1", default-features = false }
primitive-types = { version = "0.9.0", default-features = false, features = ["codec"] }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.11.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", branch = "release-polkadot-v1.11.0", default-features = false }
precompile-utils = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v1.11.0", default-features = false }

[lib]
name = "erc20"
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_prelude/std",
    "scale/std",
    "scale-info/std",
    "primitive-types/std",
    "sp-std/std",
    "sp-core/std",
    "precompile-utils/std",
]
ink-as-dependency = []
#ink-experimental-engine = ["ink_env/ink-experimental-engine"]