version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bookadot-sc-event
      POSTGRES_USER: bookadot
      POSTGRES_PASSWORD: bookadot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
