[package]
name = "pallet-signore"
description = "The pallet used for signing on behalf of others can bear the gas fee for users and lower the user threshold."
version = "0.1.0"
license = "Unlicense"
edition.workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { features = [
	"derive",
], workspace = true }
scale-info = { features = [
	"derive",
], workspace = true }
frame-benchmarking = { optional = true, workspace = true }
frame-support.workspace = true
frame-system.workspace = true
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
pallet-transaction-payment = { workspace = true }

[dev-dependencies]
sp-core = { default-features = false, workspace = true }

[features]
default = ["std"]
std = [
	"sp-std/std",
	"codec/std",
	"frame-benchmarking?/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
]

