// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAsset(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddAsset'](arg1, arg2, arg3, arg4, arg5);
}

export function AddCustomToken(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddCustomToken'](arg1, arg2, arg3, arg4, arg5);
}

export function AddLedger(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddLedger'](arg1, arg2, arg3);
}

export function CalculateFee(arg1, arg2) {
  return window['go']['main']['App']['CalculateFee'](arg1, arg2);
}

export function CheckCardConnection() {
  return window['go']['main']['App']['CheckCardConnection']();
}

export function CheckCardInitialized() {
  return window['go']['main']['App']['CheckCardInitialized']();
}

export function CheckUpdates() {
  return window['go']['main']['App']['CheckUpdates']();
}

export function ClearData(arg1, arg2) {
  return window['go']['main']['App']['ClearData'](arg1, arg2);
}

export function CurrentAccount() {
  return window['go']['main']['App']['CurrentAccount']();
}

export function DataMigrate() {
  return window['go']['main']['App']['DataMigrate']();
}

export function DoUpdate() {
  return window['go']['main']['App']['DoUpdate']();
}

export function EnableTestnet(arg1) {
  return window['go']['main']['App']['EnableTestnet'](arg1);
}

export function GetAddressAndAssets(arg1, arg2) {
  return window['go']['main']['App']['GetAddressAndAssets'](arg1, arg2);
}

export function GetAllAccounts() {
  return window['go']['main']['App']['GetAllAccounts']();
}

export function GetAssetPrices(arg1, arg2) {
  return window['go']['main']['App']['GetAssetPrices'](arg1, arg2);
}

export function GetChainConfig(arg1) {
  return window['go']['main']['App']['GetChainConfig'](arg1);
}

export function GetChainConfigs() {
  return window['go']['main']['App']['GetChainConfigs']();
}

export function GetChains(arg1) {
  return window['go']['main']['App']['GetChains'](arg1);
}

export function GetCredentials(arg1) {
  return window['go']['main']['App']['GetCredentials'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetTransactionHistory(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetTransactionHistory'](arg1, arg2, arg3, arg4, arg5);
}

export function GetWalletConnectProjectId() {
  return window['go']['main']['App']['GetWalletConnectProjectId']();
}

export function Initialize(arg1, arg2, arg3) {
  return window['go']['main']['App']['Initialize'](arg1, arg2, arg3);
}

export function Install() {
  return window['go']['main']['App']['Install']();
}

export function IsTestnetEnabled() {
  return window['go']['main']['App']['IsTestnetEnabled']();
}

export function LoadSecrePhrase(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadSecrePhrase'](arg1, arg2, arg3);
}

export function Pair(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Pair'](arg1, arg2, arg3, arg4);
}

export function RemoveAsset(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RemoveAsset'](arg1, arg2, arg3, arg4, arg5);
}

export function RemoveLedger(arg1, arg2) {
  return window['go']['main']['App']['RemoveLedger'](arg1, arg2);
}

export function ResetCard(arg1, arg2) {
  return window['go']['main']['App']['ResetCard'](arg1, arg2);
}

export function ResetWallet() {
  return window['go']['main']['App']['ResetWallet']();
}

export function SendTransaction(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SendTransaction'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SignTypedData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SignTypedData'](arg1, arg2, arg3, arg4);
}

export function Staking(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['Staking'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}

export function Teleport(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['Teleport'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function Transfer(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['Transfer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateAccountName(arg1, arg2) {
  return window['go']['main']['App']['UpdateAccountName'](arg1, arg2);
}

export function VerifyAddress(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyAddress'](arg1, arg2, arg3);
}
