- name: set performance governor
  become: true
  become_user: root
  shell: |
    echo 'GOVERNOR="performance"' | tee /etc/default/cpufrequtils
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  args:
    executable: /bin/bash

- name: set performance governor bare metal
  become: true
  become_user: root
  shell: |
    echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
  args:
    executable: /bin/bash
  ignore_errors: True