import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { headers } from 'next/headers';

import WalletProvider from '@/context/WalletProvider';
import { OrdersProvider } from '@/context/OrdersProvider';

import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css';

export const metadata: Metadata = {
    title: 'Hyper Agile',
    description: 'Generated by create next app',
};

const styreneA = localFont({
    src: [
        { path: '../../public/fonts/StyreneA-Regular.ttf', weight: '400' },
        { path: '../../public/fonts/StyreneA-Medium.ttf', weight: '500' },
        { path: '../../public/fonts/StyreneA-Bold.ttf', weight: '700' },
    ],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookies = headers().get('cookie');
    return (
        <html lang='en'>
            <WalletProvider cookies={cookies}>
                <OrdersProvider>
                    <body className={styreneA.className}>{children}</body>
                </OrdersProvider>
            </WalletProvider>
        </html>
    );
}
